name: Publish Docker Image

on:
  push:
    tags:
      - '*'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - id: prep
        run: |
          DOCKER_IMAGE=betterthings/cube:frontend
          VERSION=${GITHUB_REF#refs/tags/}
          TAG="${DOCKER_IMAGE}-${VERSION}"
          echo ::set-output name=tags::${TAG}

      - uses: docker/setup-qemu-action@v1

      - uses: docker/setup-buildx-action@v1
